export const MERMAID_COLORS = {
  nodeFill: '#dbeafe',
  nodeStroke: '#2563eb',
  nodeText: '#0f172a',
  edgeText: '#1e3a8a',
  line: '#64748b',
  actorFill: '#dbeafe',
  actorStroke: '#2563eb',
  nodeLabelFontSize: '13px',
  edgeLabelFontSize: '13px',
} as const;

export const MERMAID_THEME = {
  primaryColor: MERMAID_COLORS.nodeFill,
  primaryBorderColor: MERMAID_COLORS.nodeStroke,
  primaryTextColor: MERMAID_COLORS.nodeText,
  secondaryColor: '#ccfbf1',
  secondaryBorderColor: '#0f766e',
  secondaryTextColor: MERMAID_COLORS.nodeText,
  tertiaryColor: '#fef3c7',
  tertiaryBorderColor: '#d97706',
  tertiaryTextColor: MERMAID_COLORS.nodeText,
  lineColor: MERMAID_COLORS.line,
  textColor: MERMAID_COLORS.nodeText,
  mainBkg: '#ffffff',
  nodeBorder: MERMAID_COLORS.nodeStroke,
  clusterBkg: '#f8fafc',
  clusterBorder: '#cbd5e1',
  actorBkg: MERMAID_COLORS.actorFill,
  actorBorder: MERMAID_COLORS.actorStroke,
  actorTextColor: MERMAID_COLORS.nodeText,
  actorLineColor: MERMAID_COLORS.line,
  signalColor: MERMAID_COLORS.line,
  signalTextColor: MERMAID_COLORS.edgeText,
  labelBoxBkgColor: '#ffffff',
  labelBoxBorderColor: '#94a3b8',
  labelTextColor: MERMAID_COLORS.edgeText,
  loopTextColor: MERMAID_COLORS.nodeText,
  activationBkgColor: '#e0f2fe',
  activationBorderColor: '#0284c7',
  noteBkgColor: '#fef3c7',
  noteBorderColor: '#d97706',
  noteTextColor: MERMAID_COLORS.nodeText,
} as const;
