packages:
  - config
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true
  node-pty: true

onlyBuiltDependencies:
  - esbuild
  - node-pty

minimumReleaseAgeExclude:
  - '@finografic/project-scripts@1.6.1'
