$schema: 'https://moonrepo.dev/schemas/project.json'

language: 'typescript'

tasks:
  typecheck:
    command: 'pnpm typecheck'

  lint:
    command: 'pnpm lint'

  lint:fix:
    command: 'pnpm lint:fix'
    options:
      cache: false

  clean:
    command: 'pnpm clean'
    options:
      cache: false
