name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Configure GitHub Packages registry
        run: |
          npm config set @finografic:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: moon run root:lint-ci

      - name: Lint markdown
        run: moon run root:lint-md

      - name: Type check
        run: moon run :typecheck

      - name: Format check
        run: moon run root:format-check
