name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Configure GitHub Packages registry
        run: |
          npm config set @finografic:registry https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: moon run :build

      - name: Publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
